name: Test Workflow

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./

      - name: Setup Environment Vars
        uses: ./
        with:
          scope: dev
          input-file: './env-vars.yml'
        env:
          facts@dev qa stage prod: one
          are@dev qa stage prod: ring
          the@dev qa stage prod: to rule
          enemy_of@dev qa stage prod: them
          truth@dev qa@dev qa stage prod: all
          truth@stage prod: or it?
          in_both@dev qa stage prod: Env wins!
          sort_of_in_both@dev: Env wins!
          another_in_both@qa stage prod: Env Wins!
          something.with.periods@dev: Key Survival.
          how now@dev: brown cow?
          comma,comma,chameleon@dev: red, gold, and green

      - name: Verify Environment periods Vars
        uses: actions/github-script@v5
        with:
          script: console.log(process.env["something.with.periods"])
